name: Build & Deploy on Digital Ocean
on:
  push:
    branches:
      - main
      - feat/ci-cd
jobs:
  deploy:
    name: Build & Deploy on Digital Ocean
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Build
        uses: TartanLlama/actions-eleventy@v1.1
      - name: Deploy to Digital Ocean droplet via SSH action
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.DO_HOST }}
          username: ${{ secrets.DO_USER }}
          key: ${{ secrets.DO_KEY }}
          source: "_site/*"
          target: "/var/www/docs"
          strip_components: 1
